project_name: weatherllo

env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - make clean
    - make
builds:
  -
    id: weatherllo
    main: ./cmd/weatherllo
    binary: weatherllo

    goos:
      - darwin
      - linux

    goarch:
      - amd64


archives:
  - id: weatherllo
    replacements:
      386: i386
      amd64: x86_64
      darwin: macOS
      linux: Linux
    format: zip
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256